version: "3"

services:
  gevin:
    container_name: "gevin_bot"
    #build: .
    image: gevin:prod-latest
    environment:
      - "TZ=America/New_York"
      - LINK=$LINK
      - KEY=$KEY
    restart: always

